name: Deploy

on:
  push:
    branches: [main, dev]
  schedule:
    - cron: "0 00,12 * * *"  # Twice a day

# Default permissions for all jobs
permissions:
  packages: write
  contents: read

jobs:
  generate-matrix:
    name: Generate build matrix
    runs-on: ubuntu-latest
    needs: [test]
    outputs:
      matrix: ${{ steps.set-matrix.outputs.MATRIX }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: Generate build matrix
        run: |
          FORCE="--force"  # Force build all on first run
          uv run ninja $FORCE build-matrix --event ${{ github.event_name }}
        id: set-matrix

  deploy:
    name: ${{ matrix.key }}
    runs-on: ubuntu-latest
    if: needs.generate-matrix.outputs.matrix != ''
    needs: [generate-matrix]
    strategy:
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: Generate Dockerfile from config
        run: uv run ninja dockerfile --context '${{ toJSON(matrix) }}'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to all container registries
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfiles/${{ matrix.key }}.Dockerfile
          load: true
          tags: c0mpiler/python-nodejs:${{ matrix.key }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Run smoke tests
        run: |
          docker run --rm c0mpiler/python-nodejs:${{ matrix.key }} sh -c "node --version && npm --version && yarn --version && python --version && pip --version && pipenv --version && poetry --version && uv --version"

      - name: Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfiles/${{ matrix.key }}.Dockerfile
          platforms: ${{ join(matrix.platforms) }}
          push: true
          tags: |
            c0mpiler/python-nodejs:${{ matrix.key }}
            ghcr.io/c0mpiler/python-nodejs:${{ matrix.key }}
            quay.io/c0mpiler/python-nodejs:${{ matrix.key }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=Python with Node.js Docker Image
            org.opencontainers.image.licenses=MIT

  release:
    name: Update versions.json and README.md
    runs-on: ubuntu-latest
    needs: [deploy]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: Update versions.json and README.md, then commit and push changes (if any)
        run: |
          uv run ninja --verbose release
          clean_checkout=$(git status --porcelain)
          if [[ -n "${clean_checkout}" ]]; then
              git config --global user.name "c0mpiler" > /dev/null 2>&1
              git config --global user.email c0mpiler@ins8s.dev > /dev/null 2>&1

              # Update README.md
              today=$(date +%Y-%m-%d)
              sed -i -E "s/Last updated by bot: .*/Last updated by bot: ${today}/" README.md

              git add versions.json README.md
              git commit -m '🗃 Updated python/node versions [skip ci]'
              git push --quiet origin main
          else
              echo "Nothing changed, nothing to archive."
          fi

  test:
    uses: ./.github/workflows/tests.yaml
